services:
  compensacion-service:
    build: .
    container_name: compensacion-service
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-compensacion:5432/compensacion_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db-compensacion

  db-compensacion:
    image: postgres:15-alpine
    container_name: db-compensacion
    environment:
      - POSTGRES_DB=compensacion_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5436:5432"
